export {default as About } from './about/About';
export {default as Blog } from './blog/Blog';
export {default as BlogFull} from './blog/BlogFull';
export {default as Features } from './features/Features';
export {default as Footer } from './footer/Footer';
export {default as Header } from './header/Header';
export {default as Projects } from './projects/Projects';
export {default as ProjectsFull } from './projects/ProjectsFull';
export {default as Resume } from './resume/Resume';
export {default as Tako } from './Tako/Tako';
export {default as TakoFull} from './Tako/TakoFull';
export {default as ErrorBoundary} from './ErrorBoundary/ErrorBoundary';
